### ISSUE TITLE
ModuleNotFoundError: No module named 'isacalc.src'

### ISSUE THREAD

**Issue by NasonZ** [LukeDeWaal/ISA_Calculator#3]
Same issue as stated by others, would be nice to get this resolved as I can't find any other scripts of this quality around. 

Cheers

**Comment by pranavh** [comment]
This happens because for some reason, the wheel installed by pip doesn't contain the src directory, A workaround is to put the [src directory from this repo](https://github.com/LukeDeWaal/ISA_Calculator/tree/master/isacalc/src) in your `lib/site-packages/isacalc` directory.
